# Linear regression with multiple variable

In [8]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import linear_model

In [22]:
df=pd.read_csv(r'C:\Users\namde\Downloads\homeprices (1).csv')

In [24]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [30]:
# data preprocessing 
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

4

In [36]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [40]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [42]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [44]:
reg.intercept_

221323.0018654043

In [57]:
reg.predict([[3000,3,40]])

C:\Users\namde\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [61]:
112.06244194*3000+23388.88007794*3+-3231.71790863*40+221323.0018654043

498408.2515740243

In [63]:
reg.predict([[2500,4,5]])

C:\Users\namde\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [ ]:
# excercise
2 yr exp, 9 test score, 6 interview score
12 yr exp, 10 test score, 10 interview score

In [65]:
d=pd.read_csv(r"C:\Users\namde\Downloads\hiring.csv")

In [67]:
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [73]:
# first step data preprocessing 
d.experience=d.experience.fillna('zero')



experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [89]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [104]:
from word2number import w2n
d.experience = d.experience.astype(str)
d.experience=d.experience.apply(w2n.word_to_num)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [106]:
import math
median_test_score = math.floor(d['test_score(out of 10)'].mean())
median_test_score


7

In [108]:
d['test_score(out of 10)'] = d['test_score(out of 10)'].fillna(median_test_score)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [112]:
reg1=linear_model.LinearRegression()
reg1.fit(d[['experience','test_score(out of 10)','interview_score(out of 10)']],d['salary($)'])

LinearRegression()

In [114]:
reg1.predict([[2,9,6]])

C:\Users\namde\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [116]:
reg1.predict([[12,10,10]])

C:\Users\namde\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])

In [118]:
reg1.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [120]:
reg1.intercept_

14992.651446693126

In [163]:
# graph

